name: Events Demo 1
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main # main
      - 'feature/**' # feature/new feature/new/button
      - 'dev-/*' # dev-new dev-this-is-new
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Event Data
        run: echo "${{ toJson(github.event)}}"
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Test Code
        run: npm run test
      - name: Build Code
        run: npm run build
      - name: Deploy Project
        run: echo "Deploying Project..."